---
# tasks file for SLES12-CIS
- name: Check OS family
  fail:
      msg: "This role can only be run against SLES 12. {{ ansible_os_family }}/{{ ansible_distribution }}/{{ ansible_distribution_major_version }} is not supported."
  when:
      - not (ansible_os_family == 'Suse' and ansible_distribution_major_version in ['12','42'])
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.5 or greater
  when: ansible_version.full is version('2.5', '<')
  tags:
      - always

- include: prelim.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  tags:
      - prelim_tasks
      - always

- include: section1.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section1
  tags:
      - sles12cis_section1

- include: section2.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section2

- include: section3.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section3

- include: section4.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section4

- include: section5.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section5

- include: section6.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  when: sles12cis_section6

- include: post.yml
  become: yes
  environment:
      ZYPP_LOCK_TIMEOUT: 180
  tags:
      - post_tasks
      - always
