---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: no
  check_mode: no

- name: "PRELIM | Gather accounts with empty password fields"
  shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  register: empty_password_accounts
  changed_when: no
  failed_when: empty_password_accounts.rc > 1
  check_mode: no

- name: "PRELIM | Gather UID 0 accounts other than root"
  shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  register: uid_zero_accounts_except_root
  changed_when: no
  check_mode: no

- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd)"
  package:
      name: audit
      state: present

- name: "PRELIM | Section 5.1 | Configure cron"
  package:
      name: cronie
      state: present

- name: "PRELIM | Check if prelink package is installed"
  command: rpm -q prelink
  register: prelink_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check if postfix package is installed"
  command: rpm -q postfix
  register: postfix_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

# Individual service checks
- name: "PRELIM | Check for xinetd service"
  shell: "{{ 'service xinetd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show xinetd | grep LoadState | cut -d = -f 2' }}"
  register: xinetd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for ntpd service"
  shell: "{{ 'service ntpd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show ntpd | grep LoadState | cut -d = -f 2' }}"
  register: ntpd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for chronyd service"
  shell: "{{ 'service chronyd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show chronyd | grep LoadState | cut -d = -f 2' }}"
  register: chronyd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for avahi-daemon service"
  shell: "{{ 'service avahi-daemon status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show avahi-daemon | grep LoadState | cut -d = -f 2' }}"
  register: avahi_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for cups service"
  shell: "{{ 'service cups status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show cups | grep LoadState | cut -d = -f 2' }}"
  register: cups_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for dhcpd service"
  shell: "{{ 'service dhcpd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show dhcpd | grep LoadState | cut -d = -f 2' }}"
  register: dhcpd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for slapd service"
  shell: "{{ 'service slapd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show slapd | grep LoadState | cut -d = -f 2' }}"
  register: slapd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for nfs service"
  shell: "{{ 'service nfs status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show nfs | grep LoadState | cut -d = -f 2' }}"
  register: nfs_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for rpcbind service"
  shell: "{{ 'service rpcbind status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show rpcbind | grep LoadState | cut -d = -f 2' }}"
  register: rpcbind_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for named service"
  shell: "{{ 'service snmpd named | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show named | grep LoadState | cut -d = -f 2' }}"
  register: named_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for vsftpd service"
  shell: "{{ 'service vsftpd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show vsftpd | grep LoadState | cut -d = -f 2' }}"
  register: vsftpd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for httpd service"
  shell: "{{ 'service httpd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show httpd | grep LoadState | cut -d = -f 2' }}"
  register: httpd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for dovecot service"
  shell: "{{ 'service dovecot status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show dovecot | grep LoadState | cut -d = -f 2' }}"
  register: dovecot_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for smb service"
  shell: "{{ 'service smb status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show smb | grep LoadState | cut -d = -f 2' }}"
  register: smb_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for squid service"
  shell: "{{ 'service squid status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show squid | grep LoadState | cut -d = -f 2' }}"
  register: squid_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for snmpd service"
  shell: "{{ 'service snmpd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show snmpd | grep LoadState | cut -d = -f 2' }}"
  register: snmpd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for ypserv service"
  shell: "{{ 'service ypserv status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show ypserv | grep LoadState | cut -d = -f 2' }}"
  register: ypserv_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for rsh.socket service"
  shell: "{{ 'service rsh.socket status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show rsh.socket | grep LoadState | cut -d = -f 2' }}"
  register: rsh_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for rlogin.socket service"
  shell: "{{ 'service rlogin.socket status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show rlogin.socket | grep LoadState | cut -d = -f 2' }}"
  register: rlogin_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for rexec.socket service"
  shell: "{{ 'service rexec.socket status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show rexec.socket | grep LoadState | cut -d = -f 2' }}"
  register: rexec_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for telnet service"
  shell: "{{ 'service telnet status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show telnet | grep LoadState | cut -d = -f 2' }}"
  register: telnet_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for tftp service"
  shell: "{{ 'service tftp status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show tftp | grep LoadState | cut -d = -f 2' }}"
  register: tftp_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for rsyncd service"
  shell: "{{ 'service rsyncd status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show rsyncd | grep LoadState | cut -d = -f 2' }}"
  register: rsyncd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for ntalk service"
  shell: "{{ 'service ntalk status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show ntalk | grep LoadState | cut -d = -f 2' }}"
  register: ntalk_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for autofs service"
  shell: "{{ 'service autofs status | cut -d \" \" -f 6' if ansible_service_mgr == 'upstart' else 'systemctl show autofs | grep LoadState | cut -d = -f 2' }}"
  register: autofs_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: PRELIM | Check to see if we are booting with EFI or UEFI
  set_fact:
    booted_with_efi: "{{ ansible_facts['mounts'] | selectattr('mount', 'equalto', '/boot/efi') | list | length > 0 }}"
  changed_when: no
  check_mode: no